app_settings:
  app_type: "connector" # only lowercase letters, numbers, and underscores are allowed, e.g. salesforce, sap, zoho_crm, etc.
  app_name: "Connector Example App"
  app_icon_svg_url: "https://cdn.brandfetch.io/id9Bpy_H9O/theme/dark/idl_D0lOl6.svg?c=1dxbfHSJFAPEGdCLU4o5B" # this is the icon of the app, should be a URL pointing to a SVG file.
  app_description: "Connector Example App"
  routes_directory: "src/routes" # this is the directory where the routes are located.

local_development_settings:
  sentry_dsn: ""
  cors_origins: ["*"]
  routes_directory: "src/routes"
  debug: true
  host: "0.0.0.0"
  port: 2003
